### ISSUE TITLE
Using appimaged you get desktop files generated automatically

### ISSUE THREAD

**Issue by probonopd** [freddii/program_installers#1]
Using the optional `appimaged` daemon you get desktop files generated automatically and AppImages are set executable automatically, please see https://github.com/AppImage/appimaged. Maybe you don't need scripts then?

**Comment by freddii** [comment]
yes that is a good idea.
But https://github.com/cjcliffe/CubicSDR/releases/download/0.2.5/CubicSDR-0.2.5-x86_64.AppImage for example is still missing an icon when i use appimaged.
So that must still be manually fixed by script or is there a better solution?

**Comment by freddii** [comment]
yes that is a good idea.

But there are some bugs with appimaged:
1) Appimages are not set executeable automatically.

2) some Appimages are still missing an icon when i use appimaged. 
for example:
https://github.com/OpenShot/openshot-qt/releases/download/v2.4.3/OpenShot-v2.4.3-x86_64.AppImage
https://github.com/cjcliffe/CubicSDR/releases/download/0.2.5/CubicSDR-0.2.5-x86_64.AppImage 
https://github.com/Ultimaker/Cura/releases/download/3.6.0/Cura-3.6.0.AppImage
https://github.com/jgraph/drawio-desktop/releases/download/v9.3.1/draw.io-x86_64-9.3.1.AppImage
https://github.com/meowtec/Imagine/releases/download/v0.5.0/Imagine-0.5.0-x86_64.AppImage

3) some Appimages are still missing an icon when i use appimaged. After first run and integrating to desktop they get another starter that has an icon. So you end up with two starters. One with icon and one without.
for example:
https://github.com/laurent22/joplin/releases/download/v1.0.120/Joplin-1.0.120-x86_64.AppImage
https://github.com/balena-io/etcher/releases/download/v1.4.9/balena-etcher-electron-1.4.9-x86_64.AppImage

4) other appimages seam to have icons but whisker does not show them.
for example:
https://drawpile.net/files/appimage/Drawpile-srv-2.0.11.AppImage

5) other appimages do not show in application menu.
for example:
https://github.com/cryptomator/cryptomator/releases/download/1.4.1/cryptomator-1.4.1-x86_64.AppImage

So that must still be manually fixed by script or is there a better solution?

**Comment by probonopd** [comment]
> Appimages are not set executeable automatically.

Grave bug. But not reproducible according to https://github.com/AppImage/appimaged/issues/57

> some Appimages are still missing an icon when i use appimaged.

A bug with the affected AppImages, in case it can be reproduced it needs to be reported to the respective application projects. __Where__ is the icon missing, in the menu or on the file itself?
 
>  some Appimages are still missing an icon when i use appimaged. After first run and integrating to desktop they get another starter that has an icon. So you end up with two starters. One with icon and one without.

Can you post a screenshot please?

>  other appimages do not show in application menu.

According to https://github.com/AppImage/appimage.github.io/blob/1d25c41260855db37bb754f1a00961ca844df243/database/Cryptomator/cryptomator.desktop it should show up under "Utilities".

**Comment by freddii** [comment]
to 3.
> Can you post a screenshot please?

![openshot_without_icon_desktop_entry](https://user-images.githubusercontent.com/7213207/51779595-97198d80-2108-11e9-9663-d9d0ebac63dc.png)
![openshot_with_icon_desktop_entry](https://user-images.githubusercontent.com/7213207/51779596-9a147e00-2108-11e9-9ae3-ebe8694d2b27.png)

**Comment by freddii** [comment]
added an installer for appimaged:
https://github.com/freddii/program_installers/commit/afde55bd0fb3104743f56eba5f69351fb7fb7f6f

depricated all appimage starters:
https://github.com/freddii/program_installers/commit/270681953acce48f93de5408331086fbdc9f47e3
